name: Provision and Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    outputs:
      site_id: ${{ steps.get_outputs.outputs.site_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get Site ID
        id: get_outputs
        run: |
          echo "site_id=$(terraform output -raw site_id)" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: provision
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ needs.provision.outputs.site_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './warp/warp'  # Replace with your app's output dir (e.g., './site/build' if built)
          production-deploy: true
         